// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhBYWv-ZW-q6AkF6B_yWzMWrBBlmbh40k',
    appId: '1:346192323371:web:a35f7dc7f275cfb4229b6e',
    messagingSenderId: '346192323371',
    projectId: 'attendencetracker-e20ee',
    authDomain: 'attendencetracker-e20ee.firebaseapp.com',
    storageBucket: 'attendencetracker-e20ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6XJyPog0KW9lBu9NxcXfo-ECPgNbeRKo',
    appId: '1:346192323371:android:c6653600181525ed229b6e',
    messagingSenderId: '346192323371',
    projectId: 'attendencetracker-e20ee',
    storageBucket: 'attendencetracker-e20ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzy_16Ys8YL-TtlrI-bTsYIAJ69dP7AqY',
    appId: '1:346192323371:ios:09f87bd45f1ee5bd229b6e',
    messagingSenderId: '346192323371',
    projectId: 'attendencetracker-e20ee',
    storageBucket: 'attendencetracker-e20ee.appspot.com',
    iosBundleId: 'com.example.attendenceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzy_16Ys8YL-TtlrI-bTsYIAJ69dP7AqY',
    appId: '1:346192323371:ios:09f87bd45f1ee5bd229b6e',
    messagingSenderId: '346192323371',
    projectId: 'attendencetracker-e20ee',
    storageBucket: 'attendencetracker-e20ee.appspot.com',
    iosBundleId: 'com.example.attendenceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhBYWv-ZW-q6AkF6B_yWzMWrBBlmbh40k',
    appId: '1:346192323371:web:3ebb4528ee2e567d229b6e',
    messagingSenderId: '346192323371',
    projectId: 'attendencetracker-e20ee',
    authDomain: 'attendencetracker-e20ee.firebaseapp.com',
    storageBucket: 'attendencetracker-e20ee.appspot.com',
  );
}
